---
title: "Conteúdo"
format:
  html:
    toc: false
    anchor-sections: false
---

O conteúdo programático detalhado da disciplina é apresentado a seguir. Ele está organizado em três grandes eixos que abordaremos ao longo do semestre.

---


Parte 1: Fundamentos<br>
&ensp;&ensp;1.1. Fundamentos da Mineração de Dados<br>
&ensp;&ensp;1.2. Pré-processamento de Dados<br>
&ensp;&ensp;&ensp;&ensp;&ensp;1.2.1. Exploração<br>
&ensp;&ensp;&ensp;&ensp;&ensp;1.2.2. Limpeza<br>
&ensp;&ensp;&ensp;&ensp;&ensp;1.2.3. Transformação<br>
&ensp;&ensp;&ensp;&ensp;&ensp;1.2.3. Redução<br>

Parte 2: Aprendizado Não Supervisionado<br>
&ensp;&ensp;2.1. Regras de Associação<br>
&ensp;&ensp;2.2. $k$-means<br>

Parte 3: Aprendizado Supervisionado<br>
&ensp;&ensp;3.1. Regressão<br>
&ensp;&ensp;&ensp;&ensp;&ensp;3.1.1. Regressão linear<br>
&ensp;&ensp;&ensp;&ensp;&ensp;3.1.2. Regressão logística<br>
&ensp;&ensp;3.2. $k$-Nearest Neighbors<br>
&ensp;&ensp;3.3. Naive Bayes<br>
&ensp;&ensp;3.4. Árvores de Decisão<br>
&ensp;&ensp;3.5. Florestas aleatórias<br>
&ensp;&ensp;3.6. Support Vector Machine<br>
&ensp;&ensp;3.7. Avaliação de desempenho<br>
&ensp;&ensp;&ensp;&ensp;&ensp;3.7.1. Validação Cruzada<br>
&ensp;&ensp;&ensp;&ensp;&ensp;3.7.2. Amostragem bootstrap<br>
&ensp;&ensp;&ensp;&ensp;&ensp;3.7.3. Acurácia<br>
&ensp;&ensp;&ensp;&ensp;&ensp;3.7.4. Kappa<br>
&ensp;&ensp;&ensp;&ensp;&ensp;3.7.5. Precisão e revocação<br>
&ensp;&ensp;&ensp;&ensp;&ensp;3.7.6. Sensibilidade e especificidade<br>
&ensp;&ensp;3.8. Ajuste de parâmetros<br>
&ensp;&ensp;3.9. Métodos de conjunto (ensemble methods)<br>
&ensp;&ensp;&ensp;&ensp;&ensp;3.9.1. Bagging<br>
&ensp;&ensp;&ensp;&ensp;&ensp;3.9.2. Boosting<br>
&ensp;&ensp;&ensp;&ensp;&ensp;3.9.3. Stacking<br>