---
title: "Cronograma de Aulas"
format:
  html:
    toc: false
    anchor-sections: false
---

Confira abaixo o cronograma de aulas do semestre, baseado no [calendário acadêmico do período 2025-2](/PDFs/calendario_academico-2025-1-2.pdf){target="_blank"}.


| **Data** | **Dia da Semana** | **Aula** | **Assunto Previsto** |
|:---|:---|:---|:---------------------------|
| 07/10/25 | Terça | 1 | VI Encontro de Estatística e Ciências Atuariais da UFS |
| 09/10/25 | Quinta | 2 | Apresentação da disciplina. Revisão das principais distribuições de probabilidade |
| 14/10/25 | Terça | 3 | Amostras, Estatísticas e Estimadores |
| 16/10/25 | Quinta | 4 | Viés de um estimador |
| 21/10/25 | Terça | 5 | Erro quadrático médio de um estimador |
| 23/10/25 | Quinta | 6 | Estimadores eficientes |
| 28/10/25 | Terça | 7 | Estatísticas suficientes |
| 30/10/25 | Quinta | 8 | Critério da fatoração de Neyman |
| 04/11/25 | Terça | 9 | Família Exponencial |
| 06/11/25 | Quinta | 10 | Estatística completa e estimador não viesado de variância uniformemente mínima |
| 11/11/25 | Terça | 11 | Aula de Exercícios |
| 13/11/25 | Quinta | 12 | Avaliação 1 |
| 18/11/25 | Terça | 13 | O método dos momentos |
| 20/11/25 | Quinta | -- | Dia Nacional de Zumbi e da Consciência Negra (feriado nacional) |
| 25/11/25 | Terça | 14 | XI SEMAC |
| 27/11/25 | Quinta | 15 | XI SEMAC |
| 02/12/25 | Terça | 16 | O método dos momentos (continuação) |
| 04/12/25 | Quinta | 17 | O método da máxima verossimilhança |
| 09/12/25 | Terça | 18 | Propriedade dos estimadores de máxima verossimilhança |
| 11/12/25 | Quinta | 19 | O método da máxima verossimilhança: caso multiparamétrico |
| 16/12/25 | Terça | 20 | Exercícios |
| 18/12/25 | Quinta | 21 | Avaliação 2 |
| 23/12/25 | Terça | -- | Recesso acadêmico |
| 25/12/25 | Quinta | -- | Recesso acadêmico |
| 30/12/25 | Terça | -- | Recesso acadêmico |
| 01/01/26 | Quinta | -- | Confraternização Universal (feriado nacional) e Aniversário de São Cristóvão (feriado municipal) |
| 06/01/26 | Terça | -- | Férias coletivas para docentes |
| 08/01/26 | Quinta | -- | Férias coletivas para docentes |
| 13/01/26 | Terça | 22 | Amostras de populações normais |
| 15/01/26 | Quinta | 23 | O método da quantidade pivotal |
| 20/01/26 | Terça | 24 | Intervalos para populações normais: o caso de uma única amostra |
| 22/01/26 | Quinta | 25 | Intervalos para populações normais: duas amostras independentes |
| 27/01/26 | Terça | 26 | Intervalos para populações normais: duas amostras independentes |
| 29/01/26 | Quinta | 27 | Intervalos de confiança aproximados |
| 03/02/26 | Terça | 28 | Exercícios |
| 05/02/26 | Quinta | 29 | Exercícios |
| 10/02/26 | Terça | 30 | Avaliação 3 |
| 12/02/26 | Quinta | 31 | Avaliação Substitutiva |