---
title: "Ementa e Objetivos"
format:
  html:
    toc: false
    anchor-sections: false
---

## Ementa

Análise estatística em grandes bancos de dados. Tratamento de dados para processos de Data Mining. Principais funcionalidades, técnicas e algoritmos. Análise de associações. Classificação de dados. Árvores de decisão. Regressão Logística. Redes Neurais. Segmentação e Análise de Cluster. Estudo de casos.


## Objetivos

Capacitar o aluno a compreender, aplicar e avaliar as principais técnicas e algoritmos de mineração de dados sob uma perspectiva estatística. Ao final da disciplina, o estudante deverá ser capaz de conduzir um projeto de extração de conhecimento a partir de dados, desde a preparação e análise exploratória até a construção, interpretação e validação de modelos preditivos e descritivos, comunicando os resultados de forma clara e objetiva.

## Metodologia

Serão ministradas aulas teóricas expositivas; utilizados recursos computacionais e visuais; aplicação de métodos em dados reais; solicitação de atividades extraclasse e realização de projetos.

## Habilidades e Competências

Ao final da disciplina, espera-se que o(a) aluno(a) seja capaz de executar as rotinas essenciais de pré-processamento em grandes volumes de dados e a implementar os principais algoritmos de classificação, segmentação e associação para construir modelos preditivos e descritivos. O(A) aluno(a) também estará habilitado a avaliar criticamente a performance e a validade dos modelos gerados, bme como interpretar os resultados para extrair insights acionáveis e a comunicar suas conclusões de forma clara para diferentes públicos.

## Avaliação

Será realizada uma avaliação contínua, com solicitação de atividades extraclasse e apresentações em sala de aula. Ao final da disciplina os alunos deverão apresentar um projeto final.
